In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = '/Users/markoglodovic/Downloads/SQLFiles Tier 2/sqlite_db_pythonsqlite.db'
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [3]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, SUM( 
        CASE WHEN memid =0
        THEN guestcost * slots
        ELSE membercost * slots
        END ) AS total_revenue
        FROM Facilities
        INNER JOIN Bookings ON Facilities.facid = Bookings.facid
        GROUP BY name
        HAVING total_revenue <1000
        ORDER BY total_revenue
        LIMIT 0 , 30
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = '/Users/markoglodovic/Downloads/SQLFiles Tier 2/sqlite_db_pythonsqlite.db'
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [4]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT  M1.firstname, M1.surname,   'recommended by', M2.firstname, M2.surname 
        FROM Members AS M1
        LEFT JOIN Members AS M2 ON M1.recommendedby = M2.memid
        WHERE M2.memid !=0
        ORDER BY M1.surname, M1.firstname
        LIMIT 0 , 30
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = '/Users/markoglodovic/Downloads/SQLFiles Tier 2/sqlite_db_pythonsqlite.db'
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Florence', 'Bader', 'recommended by', 'Ponder', 'Stibbons')
('Anne', 'Baker', 'recommended by', 'Ponder', 'Stibbons')
('Timothy', 'Baker', 'recommended by', 'Jemima', 'Farrell')
('Tim', 'Boothe', 'recommended by', 'Tim', 'Rownam')
('Gerald', 'Butters', 'recommended by', 'Darren', 'Smith')
('Joan', 'Coplin', 'recommended by', 'Timothy', 'Baker')
('Erica', 'Crumpet', 'recommended by', 'Tracy', 'Smith')
('Nancy', 'Dare', 'recommended by', 'Janice', 'Joplette')
('Matthew', 'Genting', 'recommended by', 'Gerald', 'Butters')
('John', 'Hunt', 'recommended by', 'Millicent', 'Purview')
('David', 'Jones', 'recommended by', 'Janice', 'Joplette')
('Douglas', 'Jones', 'recommended by', 'David', 'Jones')
('Janice', 'Joplette', 'recommended by', 'Darren', 'Smith')
('Anna', 'Mackenzie', 'recommended by', 'Darren', 'Smith')
('Charles', 'Owen', 'recommended by', 'Darren', 'Smith')
('David', 'Pinker', 'recommended by', 'Jemima', 'Farrell')
('Millicent', 'Purview', 'recommended by', 'Tracy', 'Smith')
('Henrietta', 'Rumney', 'recommended by', 'Matthew', 'Genting')
('Ramnaresh', 'Sarwin', 'recommended by', 'Florence', 'Bader')
('Jack', 'Smith', 'recommended by', 'Darren', 'Smith')
('Ponder', 'Stibbons', 'recommended by', 'Burton', 'Tracy')
('Henry', 'Worthington-Smyth', 'recommended by', 'Tracy', 'Smith')

In [5]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT fac.name AS facility, memb.bookings AS member_usage
        FROM (

        SELECT facid, name
        FROM Facilities
        ) AS fac
        INNER JOIN (

        SELECT facid, COUNT( * ) AS bookings
        FROM Bookings
        WHERE memid !=0
        GROUP BY facid
        ) AS memb ON fac.facid = memb.facid 
            """
    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = '/Users/markoglodovic/Downloads/SQLFiles Tier 2/sqlite_db_pythonsqlite.db'
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', 308)
('Tennis Court 2', 276)
('Badminton Court', 344)
('Table Tennis', 385)
('Massage Room 1', 421)
('Massage Room 2', 27)
('Squash Court', 195)
('Snooker Table', 421)
('Pool Table', 783)

In [6]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT
strftime('%m', b.starttime) AS month,
f.name AS facility,
sum(slots) as usage
FROM Bookings as b
LEFT JOIN Facilities AS f
ON b.facid = f.facid
LEFT JOIN Members AS m
ON b.memid = m.memid
WHERE b.memid <> 0
GROUP BY month, f.name;
            """
    
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = '/Users/markoglodovic/Downloads/SQLFiles Tier 2/sqlite_db_pythonsqlite.db'
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 165)
('07', 'Massage Room 1', 166)
('07', 'Massage Room 2', 8)
('07', 'Pool Table', 110)
('07', 'Snooker Table', 140)
('07', 'Squash Court', 50)
('07', 'Table Tennis', 98)
('07', 'Tennis Court 1', 201)
('07', 'Tennis Court 2', 123)
('08', 'Badminton Court', 414)
('08', 'Massage Room 1', 316)
('08', 'Massage Room 2', 18)
('08', 'Pool Table', 303)
('08', 'Snooker Table', 316)
('08', 'Squash Court', 184)
('08', 'Table Tennis', 296)
('08', 'Tennis Court 1', 339)
('08', 'Tennis Court 2', 345)
('09', 'Badminton Court', 507)
('09', 'Massage Room 1', 402)
('09', 'Massage Room 2', 28)
('09', 'Pool Table', 443)
('09', 'Snooker Table', 404)
('09', 'Squash Court', 184)
('09', 'Table Tennis', 400)
('09', 'Tennis Court 1', 417)
('09', 'Tennis Court 2', 414)